services:
  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - C:\Users\andre\Downloads\Currency:/var/lib/postgresql/data
    networks:
      - mynetwork
  currency-converter:
    image: currencydemo:4.5.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - C:\Users\andre\Downloads\Currency2:/Users/andre/Downloads/Currency3
    depends_on:
      - postgres
    networks:
      - mynetwork
  angular:
    image: angular-software:5.4.0
    ports:
      - "4200:80"
    volumes:
      - C:\Users\andre\Downloads\software-main\nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16
          gateway: 172.15.0.1